require(XML)
require(ggplot2)
require(ggridges)
require(gridExtra)
filename <- file.choose()
source("pubmedXML2df.R")
theData <- extract_xml(filename)
write.csv(theData, file = "pubmed_data.csv")
theData$recacc <-as.numeric(theData$accdate - theData$recdate)
theData$recpub <-as.numeric(theData$pubdate - theData$recdate)
theData$accpub <-as.numeric(theData$pubdate - theData$accdate)
# multi-year comparison
p1 <- ggplot(theData, aes(x = recacc, y = year, group = year)) + geom_density_ridges() + xlim(0,730) + labs(x = "Received-Accepted (days)") + theme(axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold"))
p2 <- ggplot(theData, aes(x = recpub, y = year, group = year)) + geom_density_ridges() + xlim(0,730) + labs(x = "Received-Published (days)") + theme(axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold"))
p3 <- ggplot(theData, aes(x = accpub, y = year, group = year)) + geom_density_ridges() + xlim(0,730) + labs(x = "Accepted-Published (days)") + theme(axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold"))
p4 <- ggplot(theData, aes(x = pubdate, y = recacc)) + geom_point(alpha = 0.2,size = 0.3) + geom_smooth(color = "orange") + labs(x = "Publication date", y = "Received-Accepted (days)") + theme(axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold"))
png("yearPlot.png", width = 1000, height = 1000)
grid.arrange(p1, p2, p3, p4, nrow = 2)
dev.off()
